# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_prior_stat <- function(omega, etas, R, draws, burnin, thin, quantile) {
    .Call('_multimetab_get_prior_stat', PACKAGE = 'multimetab', omega, etas, R, draws, burnin, thin, quantile)
}

bvs_mcmc <- function(y, X, psi, hyper_params, R, theta2, reps, burnin, thinning, infer_delta, refine_betas, adaptive, vs, adapt_prop, beta0_samples, beta_samples, gamma_samples, sigma2_samples, delta_samples, rho_samples, acceptance, moves, pt_check, pmax, pmax_draws) {
    invisible(.Call('_multimetab_bvs_mcmc', PACKAGE = 'multimetab', y, X, psi, hyper_params, R, theta2, reps, burnin, thinning, infer_delta, refine_betas, adaptive, vs, adapt_prop, beta0_samples, beta_samples, gamma_samples, sigma2_samples, delta_samples, rho_samples, acceptance, moves, pt_check, pmax, pmax_draws))
}

